### ISSUE TITLE
PodDisruptionBudget for system workloads

### ISSUE THREAD

**Issue by Miradorn** [superluminar-io/super-eks#59]
Add PodDisruption Budgets to workloads in kube-system.

### Use Case

The cluster autoscaler doesn't evict pods from kube-system (system-pods, e.g. CoreDNS) by default.
This can be enabled by either:

* Adding PodDisruptionBudgets for them
* Adding the `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation to them
* 
Since the second option only works for Workloads that we are provisioning ourself, we should opt into the first one for pre-provisioned workloads

### Proposed Solution

smth like

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: coredns-pdb
  namespace: kube-system
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
```

* [x] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request
